### ISSUE TITLE
Release ToDo

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#256]
- [ ] Implement card order
 - [ ] Show something on card selections
 - [ ] Maybe add network timeout and no connection screen

**Comment by thellmund** [comment]
For item 4: What’s the desired behavior? Should News only display non-newsspread items?

**Comment by TG908** [comment]
yes

**Comment by thellmund** [comment]
Done in #271.

**Comment by thellmund** [comment]
Fixing the poster size is in progress in #273.

**Comment by thellmund** [comment]
Please don’t keep adding to this list. There are always things we could be doing before release, but then we’ll never release anything.
