### ISSUE TITLE
Problems / Bugs from Userfeedback

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#70]
- [x] Unter more ganz oben wo anfangs der Name stand, steht jetzt nichts mehr #118
- [x] Klicke ich auf das Defaultbild im Kreis stürzt die App ab #118
- [ ] Noten, Tuition und Vorlesungen werden nicht mehr angezeigt (bei der ersten Benutzung der App wurden diese noch angezeigt)
- [x] Service und Default Campus lassen sich nicht öffnen #80

**Comment by mammuth** [comment]
> Service und Default Campus lassen sich nicht öffnen
Those features aren't implemented 🙈 So we should just hide these buttons in the More view

All other three issues sound like the app does not have access to TUMOnline anymore.

**Comment by kordianbruck** [comment]
Well damn, why were those deployed :construction: :building_construction: 

Is there a sync issue that the token is somehow not saved maybe? Or overwritten?

**Comment by TG908** [comment]
not relevant anymore since the whole model and network layer has changed
